environment:
  TREE_SITTER_TEST: true

build: false

install:
  - git submodule update --init --recursive

  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain stable
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

  - script\fetch-fixtures.cmd

test_script:
  - cargo build
  - cargo test

branches:
  only:
    - master

cache:
  - target
  - test\fixtures\grammars
  - C:\Users\appveyor\.cargo
