build: false
install:
  # Install rust
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain stable
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV

  # Install dependencies
  - git submodule update --init

platform:
  - x64
  - x86

test_script:
  # Fetch and regenerate the fixture parsers
  - script\fetch-fixtures.cmd
  - cargo build --release
  - script\regenerate-fixtures.cmd

  # Run tests
  - set TREE_SITTER_TEST=1
  - script\test.cmd

branches:
  only:
    - master
    - /\d+\.\d+\.\d+.*/

before_deploy:
  - move target\release\tree-sitter.exe tree-sitter.exe
  - 7z a tree-sitter-windows-%PLATFORM%.zip tree-sitter.exe
  - appveyor PushArtifact tree-sitter-windows-%PLATFORM%.zip

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: VC9ntV5+inKoNteZyLQksKzWMKXF46P+Jx3JHKVSfF+o1rWtZn2iIHAVsQv5LaUi
  artifact: /tree-sitter-windows-.*.zip/
  draft: true
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true

cache:
  - target
  - test\fixtures\grammars
  - C:\Users\appveyor\.cargo
  - C:\cargo\registry
  - C:\cargo\git
