environment:
  RUST_BACKTRACE: full
  TREE_SITTER_TEST: true

build: false

install:
  # Install rust
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain stable
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV

  # Install dependencies
  - git submodule update --init
  - script\fetch-fixtures.cmd

test_script:
  - cargo build
  - cargo test

branches:
  only:
    - master

cache:
  - target
  - test\fixtures\grammars
  - C:\Users\appveyor\.cargo
  - C:\cargo\registry
  - C:\cargo\git
