language: rust

rust:
  - stable

env:
  - TREE_SITTER_TEST=1

before_install:
  - ./script/fetch-fixtures

branches:
  only:
  - master

cache:
  cargo: true
  directories:
    - test/fixtures/grammars
