language: cpp
compiler:
    - gcc
before_install:
  - sudo apt-get install libboost-regex1.48-dev
install: script/configure.sh -D USE_BOOST_REGEX=true -D USE_LIBPROFILER=false
script: script/test_all.sh
