language: rust
rust:
  - beta

os:
  - linux
  - osx

script:
  # Fetch and regenerate the fixture parsers
  - script/fetch-fixtures
  - cargo build --release
  - script/regenerate-fixtures

  # Run tests
  - export TREE_SITTER_STATIC_ANALYSIS=1
  - script/test
  - script/benchmark

branches:
  only:
  - master
  - /\d+\.\d+\.\d+/

before_deploy:
  - cp target/release/tree-sitter .
  - gzip --suffix "-${TRAVIS_OS_NAME}-x64.gz" tree-sitter

deploy:
  provider: releases
  api_key:
    secure: "cAd2mQP+Q55v3zedo5ZyOVc3hq3XKMW93lp5LuXV6CYKYbIhkyfym4qfs+C9GJQiIP27cnePYM7B3+OMIFwSPIgXHWWSsuloMtDgYSc/PAwb2dZnJqAyog3BohW/QiGTSnvbVlxPF6P9RMQU6+JP0HJzEJy6QBTa4Und/j0jm24="
  file_glob: true
  file: "tree-sitter-*.gz"
  draft: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true

cache:
  cargo: true
  directories:
    - test/fixtures/grammars
