language: rust
rust:
  - stable

script:
  # Fetch and regenerate the fixture parsers
  - script/fetch-fixtures
  - cargo build --release
  - script/regenerate-fixtures

  # Run tests
  - export TREE_SITTER_STATIC_ANALYSIS=1
  - script/test

branches:
  only:
  - master

cache:
  cargo: true
  directories:
    - test/fixtures/grammars
