[package]
name = "tree-sitter"
description = "Rust bindings to the Tree-sitter parsing library"
version = "0.1.0"
authors = ["Max Brunsfeld <maxbrunsfeld@gmail.com>"]
build = "build.rs"
license = "MIT"
include = [
  "/build.rs",
  "/Cargo.toml",
  "/LICENSE",
  "/README.md",
  "/src/*",
  "/vendor/tree-sitter/externals/utf8proc/utf8proc*",
  "/vendor/tree-sitter/include/*",
  "/vendor/tree-sitter/src/runtime/*",
]

[build-dependencies]
cc = "1.0"
