[package]
name = "rust-tree-sitter-cli"
version = "0.1.0"
authors = ["Max Brunsfeld <maxbrunsfeld@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
smallbitvec = "2.3.0"
clap = "2.32"
dirs = "1.0.2"
ignore = "0.4.4"
libloading = "0.5"
rusqlite = "0.14.0"
serde = "1.0"
serde_derive = "1.0"
tree-sitter = "0.3.1"
regex-syntax = "0.6.4"

[dependencies.serde_json]
version = "1.0"
features = ["preserve_order"]
